firstforum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^topics/(\d+)$', views.contopic),
    url(r'^topics/addlike/(\d+)$', views.addlike),
    url(r'^topics/adddislike/(\d+)$', views.adddislike),
    url(r'^topics/addcomment/(\d+)$', views.addcomment, name='add_comment'),
    url(r'^login$', views.login),
    url(r'^logout$', views.logout),
    url(r'^register$', views.register),
    url(r'^view/(\S+)$', views.viewacc),
    url(r'^messages/new$', views.dialog_new, name='private_messages_new'),
    url(r'^messages$', views.dialogs, name='private_messages'),
    url(r'^pm_dialog-(\d+)$', views.dialog_read),
    url(r'^ajax$', views.ajaxtest),
    url(r'^$', views.indexpage),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from base64 import b16encode


class DialogManager(models.Manager):
    def by_user(self, user):
        """
        Возвращает все сообщения пользователя (идет во вьюхи)
        """
        return self.filter(models.Q(sender=user) | models.Q(recipient=user))


class Section(models.Model):
    section_header = models.CharField(max_length=40)

    class Meta:
        db_table = 'section'

    def __str__(self):
        return self.section_header


def upload_location(i, imgname):
    enc = b16encode(imgname.encode('utf-8'))
    enc = enc.decode('utf-8')
    return '%s/%s/%s' % (enc[:2], enc[2:4], imgname)


class Topic(models.Model): # Here should be relations to category.
    topic_section = models.ForeignKey(Section, on_delete=models.CASCADE)
    topic_header = models.CharField(max_length=30)
    topic_text = models.TextField()
    topic_rate_plus = models.IntegerField(default=0)
    topic_rate_minus = models.IntegerField(default=0)
    topic_pub_date = models.DateTimeField(auto_now_add=True)
    topic_edit_date = models.DateTimeField(null=True)
    topic_pic = models.ImageField(default='default_topic_pic.png',
                                  upload_to=upload_location,
                                  width_field='width',
                                  height_field='height')
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)

    class Meta:
        db_table = 'topic'

    def __str__(self):
        return self.topic_header


class TopicComments(models.Model):
    comments_topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    comments_text = models.TextField(max_length=800)
    comments_pub_date = models.DateTimeField(auto_now_add=True)
    comments_edit_date = models.DateTimeField(null=True)
    comments_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'comments'

    def __str__(self):
        return self.comments_text


class Dialog(models.Model):
    sender = models.ForeignKey(User, related_name='pm_sender')
    recipient = models.ForeignKey(User, related_name='pm_recipient')
    subject = models.CharField(max_length=255)

    objects = DialogManager()

    class Meta:
        db_table = 'dialog'

    def __str__(self):
        return 'dialog %s' % self.id

    def get_absolute_url(self):
        return 'pm_dialog-' + str(self.pk)


class PrivateMessage(models.Model):
    sender = models.ForeignKey(User, related_name='sender')
    dialog = models.ForeignKey(Dialog, related_name='messages')
    text = models.TextField(max_length=1500)
    date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'messages'

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return '%s#message-%s' % (self.dialog.get_absolute_url(), self.pk)


class Category(models.Model): # Here should be MPTT module. But not in this "project".
    category_name = models.CharField(max_length=100)
    category_related = models.ForeignKey('self', null=True, blank=True)
    category_included = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return '>>' * self.category_included + ' %s' % self.category_name

forum/forms.py
from django import forms
from forum.models import TopicComments, PrivateMessage
from django.contrib.auth.models import User


class CommentsForm(forms.ModelForm):
    class Meta:
        model = TopicComments
        fields = ['comments_text']


class MessageSendForm(forms.ModelForm):
    class Meta:
        model = PrivateMessage
        fields = ('text',)


class NewDialogForm(MessageSendForm):
    recipient = forms.CharField(label='Recipient', help_text='Specify the username')
    subject = forms.CharField(label='Subject')

    def clean_recipient(self):
        try:
            recipient = User.objects.get(username=self.cleaned_data['recipient'])
        except User.DoesNotExist:
            raise forms.ValidationError('Username not found')

        return recipient

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from forum.models import Topic, TopicComments, PrivateMessage, Dialog
from django.db.models import F
from django.contrib import auth
from django.contrib.auth.models import User
from django.template.context_processors import csrf
from django.contrib.auth.forms import UserCreationForm
from forum.forms import CommentsForm, NewDialogForm, MessageSendForm


def indexpage(request):
    """ Список топиков (пока что) """
    args = {
        'topics': Topic.objects.all(),
    }
    return render(request, 'forum/index.html', args)


def contopic(request, topic_id):
    """ Открывает выбранный топик """
    args = {
        'topic': get_object_or_404(Topic, id=topic_id),
        'comments': TopicComments.objects.filter(comments_topic=topic_id),
        'form': CommentsForm,
    }
    args.update(csrf(request))
    return render(request, 'forum/topic.html', args)


def addlike(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    topic.topic_rate_plus=F('topic_rate_plus') + 1
    topic.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def adddislike(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    topic.topic_rate_minus=F('topic_rate_minus') + 1
    topic.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def viewacc(request, name_or_id):
    if name_or_id.isnumeric():
        args = {'userview': get_object_or_404(User, id=name_or_id), 'req': request}
    else:
        args = {'userview': get_object_or_404(User, username=name_or_id), 'req': request}
    return render(request, 'forum/userprofile.html', args)


def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect('/')
        else:
            args['login_error'] = 'User not found'
            return render(request, 'forum/login.html', args)
    else:
        return render(request, 'forum/login.html', args)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def addcomment(request, topic_id):
    if request.POST:
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comments_topic = Topic.objects.get(id=topic_id)
            comment.comments_by = request.user
            form.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm
    if request.POST:
        newuser = UserCreationForm(request.POST)
        if newuser.is_valid():
            newuser.save()
            newuser = auth.authenticate(
                username=newuser.cleaned_data['username'],
                password=newuser.cleaned_data['password1']
            )
            auth.login(request, newuser)
            return HttpResponseRedirect('/')
        else:
            args['form'] = newuser
    return render(request, 'forum/register.html', args)

# Отсюда идут вьюхи для теста и понимания устройства нового модуля


#def messages(request):
#    """ Возвращает пользователю все его отправленные/полученные сообщения """
#    args = {'messages': PrivateMessage.objects.by_user(request.user)}
#   # Пытаюсь заставить джангу достать все сообщения пользователя
#    return render(request, 'forum/privatemessages.html', args)


def dialogs(request):
    return render(request, 'forum/dialog/dialogs.html', {
        'dialogs': Dialog.objects.by_user(request.user)
    })


def dialog_read(request, dialog_id):
    dialog = get_object_or_404(Dialog.objects.by_user(request.user), id=dialog_id)

    if request.method == 'POST':
        form = MessageSendForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.dialog = dialog
            message.sender = request.user
            message.save()

            dialog.save()

            return HttpResponseRedirect(message.get_absolute_url())
    else:
        form = MessageSendForm()

        # помечаем сообщения как прочитанные
    # PrivateMessage.objects.mark_read(request.user, dialog)

    return render(request, 'forum/dialog/dialog_read.html', {
        'pm_topic': dialog,
        'pm_form': form,
    })


def dialog_new(request):
    if request.method == 'POST':
        form = NewDialogForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)

            dialog = Dialog(sender=request.user)
            dialog.recipient = form.cleaned_data['recipient']
            dialog.subject = form.cleaned_data['subject']
            dialog.save()

            message.dialog = dialog
            message.sender = request.user
            message.save()

            return HttpResponseRedirect('/')
    else:
        initial = {}
        if request.GET.__contains__('recipient'):
            initial['recipient'] = request.GET['recipient']

        form = NewDialogForm(initial=initial)

    return render(request, 'forum/dialog/dialog_new.html', {
        'pm_form': form
    })


def ajaxtest(request):
    if request.GET:
        if request.GET['de_wei'] == 'de wei':
            return HttpResponse('You do not know de wei...')
        else:
            return HttpResponse(request.GET['de_wei'])
    return render(request, 'forum/ajax/ajax.html')

templates/forum/dialog/base.html
{% extends "forum/base.html" %}

{% block content %}
    <div class="row">
        <h2>Личные сообщения</h2>

        {% block pm_menu %}{% endblock %}

        <div class="span-20">
            {% block pm_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

templates/forum/dialog/dialog_new.html
{% extends "forum/dialog/base.html" %}

{% block pm_menu %}
    <ul class="nav nav-tabs">
        <li><a href="{% url 'private_messages' %}">Личные сообщения</a></li>
        <li class="active"><a href="{% url 'private_messages_new' %}">Написать</a></li>
    </ul>
{% endblock %}

{% block pm_content %}
    {% if pm_form.errors %}
        <div class="alert alert-error">
            {{ pm_form.errors }}
        </div>
    {% endif %}

    <form action="{% url 'private_messages_new' %}" method="post" class="form-horizontal">{% csrf_token %}
        <fieldset>
            <div class="control-group">
                <label class="control-label" for="id_recipient">Кому:</label>
                <div class="controls">
                    {{ pm_form.recipient }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_subject">Тема сообщения:</label>
                <div class="controls">
                    {{ pm_form.subject }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_body">Текст:</label>
                <div class="controls">
                    {{ pm_form.text }}
                </div>
            </div>
        </fieldset>
        
        <input type="submit" class="btn" value="Отправить">
    </form>
{% endblock %}

templates/forum/dialog/dialog_read.html
{% extends "forum/dialog/base.html" %}

{% block pm_menu %}
    <ul class="nav nav-tabs">
        <li><a href="{% url 'private_messages' %}">Личные сообщения</a></li>
        <li><a href="{% url 'private_messages_new' %}">Написать</a></li>
        <li class="active"><a href="#">{{ pm_topic.subject }}</a></li>
    </ul>
{% endblock %}

{% block pm_content %}
    <div class="row"><div class="span12">
        <h3>Тема: {{ pm_topic.subject }}</h3>

        <form action="{{ pm_topic.get_absolute_url }}" method="post">{% csrf_token %}
            <fieldset>
                <div class="control-group">
                    <label class="control-label" for="id_body">Текст:</label>
                    <div class="controls">
                        {{ pm_form.text }}
                    </div>
                </div>
            </fieldset>

            <input type="submit" class="btn" value="Отправить">
        </form>
        <table class="table" width="100%">
            {% for message in pm_topic.messages.all %}
                <tr>
                    <td width="100px">
                        {{ message.sender.username }}<br />
                        {{ message.sent_at|date:"d.m.Y H:i" }}
                    </td>
                    <td>{{ message.text }}</td>
                </tr>
            {% endfor %}
        </table>
    </div></div>
{% endblock %}

templates/forum/dialog/dialogs.html
{% extends "forum/dialog/base.html" %}

{% block pm_menu %}
    <ul class="nav nav-tabs">
        <li class="active"><a href="{% url 'private_messages' %}">Личные сообщения</a></li>
        <li><a href="{% url 'private_messages_new' %}">Написать</a></li>
    </ul>
{% endblock %}

{% block pm_content %}
    <div class="row"><div class="span12">
        <form action="#" method="post">{% csrf_token %}
            <table class="table">
                <tr>
                    <th>Тема</th>
                    <th>Кому адресованно</th>
                    <th>Статус</th>
                    <th>Дата</th>
                    <th>Удалить</th>
                </tr>
                {% for topic in dialogs %}
                    <tr>
                        <td><a href="{{ topic.get_absolute_url }}">{{ topic.subject }}</a></td>
                        <td>
                            {% ifequal topic.sender user %}
                                {{ topic.recipient }} <span>от меня</span>
                            {% else %}
                                <span>Мне от</span> {{ topic.sender }}
                            {% endifequal %}
                        </td>
                        <td>
                            {% if topic.count_unread_messages %}
                                {% ifequal topic.last_unread_message.sender user %}
                                    <span class="badge badge-success">Отправлено</span>
                                {% else %}
                                    <span class="badge badge-important">Новое</span>
                                {% endifequal %}
                            {% else %}
                                <span class="badge">Прочитано</span>
                            {% endif %}
                        </td>
                        <td>{{ topic.last_sent_at|date:"d M, H:i:s" }}</td>
                        <td><input type="checkbox" name="topic[]" value="{{ topic.id }}" /></td>
                    </tr>
                {% endfor %}
            </table>

            <p style="text-align:right;">
                <input type="submit" value="Удалить" />
            </p>
        </form>
    </div></div>
{% endblock %}