firstforum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^topics/(\d+)$', views.contopic),
    url(r'^topics/addlike/(\d+)$', views.addlike),
    url(r'^topics/adddislike/(\d+)$', views.adddislike),
    url(r'^topics/addcomment/(\d+)$', views.addcomment, name='add_comment'),
    url(r'^login$', views.login),
    url(r'^logout$', views.logout),
    url(r'^register$', views.register),
    url(r'^view/(\S+)$', views.viewacc),
    url(r'^messages/new$', views.dialog_new, name='private_messages_new'),
    url(r'^messages$', views.dialogs, name='private_messages'),
    url(r'^pm_dialog-(\d+)$', views.dialog_read),
    url(r'^ajax$', views.ajaxtest),
    url(r'^$', views.indexpage),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from base64 import b16encode


class DialogManager(models.Manager):
    def by_user(self, user):
        """
        Возвращает все сообщения пользователя (идет во вьюхи)
        """
        return self.filter(models.Q(sender=user) | models.Q(recipient=user))


class Section(models.Model):
    section_header = models.CharField(max_length=40)

    class Meta:
        db_table = 'section'

    def __str__(self):
        return self.section_header


def upload_location(i, imgname):
    enc = b16encode(imgname.encode('utf-8'))
    enc = enc.decode('utf-8')
    return '%s/%s/%s' % (enc[:2], enc[2:4], imgname)


class Topic(models.Model): # Here should be relations to category.
    topic_section = models.ForeignKey(Section, on_delete=models.CASCADE)
    topic_header = models.CharField(max_length=30)
    topic_text = models.TextField()
    topic_rate_plus = models.IntegerField(default=0)
    topic_rate_minus = models.IntegerField(default=0)
    topic_pub_date = models.DateTimeField(auto_now_add=True)
    topic_edit_date = models.DateTimeField(null=True)
    topic_pic = models.ImageField(default='default_topic_pic.png',
                                  upload_to=upload_location,
                                  width_field='width',
                                  height_field='height')
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)

    class Meta:
        db_table = 'topic'

    def __str__(self):
        return self.topic_header


class TopicComments(models.Model):
    comments_topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    comments_text = models.TextField(max_length=800)
    comments_pub_date = models.DateTimeField(auto_now_add=True)
    comments_edit_date = models.DateTimeField(null=True)
    comments_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'comments'

    def __str__(self):
        return self.comments_text


class Dialog(models.Model):
    sender = models.ForeignKey(User, related_name='pm_sender')
    recipient = models.ForeignKey(User, related_name='pm_recipient')
    subject = models.CharField(max_length=255)

    objects = DialogManager()

    class Meta:
        db_table = 'dialog'

    def __str__(self):
        return 'dialog %s' % self.id

    def get_absolute_url(self):
        return 'pm_dialog-' + str(self.pk)


class PrivateMessage(models.Model):
    sender = models.ForeignKey(User, related_name='sender')
    dialog = models.ForeignKey(Dialog, related_name='messages')
    text = models.TextField(max_length=1500)
    date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'messages'

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return '%s#message-%s' % (self.dialog.get_absolute_url(), self.pk)


class Category(models.Model): # Here should be MPTT module. But not in this "project".
    category_name = models.CharField(max_length=100)
    category_related = models.ForeignKey('self', null=True, blank=True)
    category_included = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return '>>' * self.category_included + ' %s' % self.category_name

forum/forms.py
from django import forms
from forum.models import TopicComments, PrivateMessage
from django.contrib.auth.models import User


class CommentsForm(forms.ModelForm):
    class Meta:
        model = TopicComments
        fields = ['comments_text']


class MessageSendForm(forms.ModelForm):
    class Meta:
        model = PrivateMessage
        fields = ('text',)


class NewDialogForm(MessageSendForm):
    recipient = forms.CharField(label='Recipient', help_text='Specify the username')
    subject = forms.CharField(label='Subject')

    def clean_recipient(self):
        try:
            recipient = User.objects.get(username=self.cleaned_data['recipient'])
        except User.DoesNotExist:
            raise forms.ValidationError('Username not found')

        return recipient

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from forum.models import Topic, TopicComments, PrivateMessage, Dialog
from django.db.models import F
from django.contrib import auth
from django.contrib.auth.models import User
from django.template.context_processors import csrf
from django.contrib.auth.forms import UserCreationForm
from forum.forms import CommentsForm, NewDialogForm, MessageSendForm


def indexpage(request):
    """ Список топиков (пока что) """
    args = {
        'topics': Topic.objects.all(),
    }
    return render(request, 'forum/index.html', args)


def contopic(request, topic_id):
    """ Открывает выбранный топик """
    args = {
        'topic': get_object_or_404(Topic, id=topic_id),
        'comments': TopicComments.objects.filter(comments_topic=topic_id),
        'form': CommentsForm,
    }
    args.update(csrf(request))
    return render(request, 'forum/topic.html', args)


def addlike(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    topic.topic_rate_plus=F('topic_rate_plus') + 1
    topic.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def adddislike(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    topic.topic_rate_minus=F('topic_rate_minus') + 1
    topic.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def viewacc(request, name_or_id):
    if name_or_id.isnumeric():
        args = {'userview': get_object_or_404(User, id=name_or_id), 'req': request}
    else:
        args = {'userview': get_object_or_404(User, username=name_or_id), 'req': request}
    return render(request, 'forum/userprofile.html', args)


def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect('/')
        else:
            args['login_error'] = 'User not found'
            return render(request, 'forum/login.html', args)
    else:
        return render(request, 'forum/login.html', args)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def addcomment(request, topic_id):
    if request.POST:
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comments_topic = Topic.objects.get(id=topic_id)
            comment.comments_by = request.user
            form.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm
    if request.POST:
        newuser = UserCreationForm(request.POST)
        if newuser.is_valid():
            newuser.save()
            newuser = auth.authenticate(
                username=newuser.cleaned_data['username'],
                password=newuser.cleaned_data['password1']
            )
            auth.login(request, newuser)
            return HttpResponseRedirect('/')
        else:
            args['form'] = newuser
    return render(request, 'forum/register.html', args)

# Отсюда идут вьюхи для теста и понимания устройства нового модуля


#def messages(request):
#    """ Возвращает пользователю все его отправленные/полученные сообщения """
#    args = {'messages': PrivateMessage.objects.by_user(request.user)}
#   # Пытаюсь заставить джангу достать все сообщения пользователя
#    return render(request, 'forum/privatemessages.html', args)


def dialogs(request):
    return render(request, 'forum/dialog/dialogs.html', {
        'dialogs': Dialog.objects.by_user(request.user)
    })


def dialog_read(request, dialog_id):
    dialog = get_object_or_404(Dialog.objects.by_user(request.user), id=dialog_id)

    if request.method == 'POST':
        form = MessageSendForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.dialog = dialog
            message.sender = request.user
            message.save()

            dialog.save()

            return HttpResponseRedirect(message.get_absolute_url())
    else:
        form = MessageSendForm()

        # помечаем сообщения как прочитанные
    # PrivateMessage.objects.mark_read(request.user, dialog)

    return render(request, 'forum/dialog/dialog_read.html', {
        'pm_topic': dialog,
        'pm_form': form,
    })


def dialog_new(request):
    if request.method == 'POST':
        form = NewDialogForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)

            dialog = Dialog(sender=request.user)
            dialog.recipient = form.cleaned_data['recipient']
            dialog.subject = form.cleaned_data['subject']
            dialog.save()

            message.dialog = dialog
            message.sender = request.user
            message.save()

            return HttpResponseRedirect('/')
    else:
        initial = {}
        if request.GET.__contains__('recipient'):
            initial['recipient'] = request.GET['recipient']

        form = NewDialogForm(initial=initial)

    return render(request, 'forum/dialog/dialog_new.html', {
        'pm_form': form
    })


def ajaxtest(request):
    if request.GET:
        if request.GET['de_wei'] == 'de wei':
            return HttpResponse('You do not know de wei...')
        else:
            return HttpResponse(request.GET['de_wei'])
    return render(request, 'forum/ajax/ajax.html')

templates/forum/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Default title{% endblock %}</title>
    <link href="{% block style %}{% static 'css/style.css' %}{% endblock %}" rel="stylesheet">
    {% block head %}{% endblock %}
</head>

<body>
<header><h1><strong>The forum. Welcome. Again.</strong></h1></header>

<div class="userpanel">
    <a href="/" class="messages">To home</a>

    {% if user.username %}
        <a href="/messages" class="messages">| Мои сообщения</a>
        <a href="/logout" class="login">Выйти ({{ user.username }})</a>
    {% else %}
        <a href="/login" class="login">Войти</a>
    {% endif %}
    {% if user.is_superuser %}
        <a href="/admin" class="messages">Admin-panel</a>
    {% endif %}
</div>
<hr>
<main>
    {% block content %}<p>Some... </p><h2>BODY ONCE TOLD ME DE WORLD IS GONNA ROLL ME</h2>{% endblock %}
</main>
</body>
</html>

templates/forum/index.html
{% extends 'forum/base.html' %}
{% load static %}

{% block head %}
    <script type="text/javascript" src={% static 'js/jquery.js' %}></script>
    <script type="text/javascript" src={% static 'js/index_script.js' %}></script>
{% endblock %}

{% block content %}
    <tr>
    <table class="indextable">
        <tbody>
            {% for topic in topics %}
                <tr>
                    <td class="header">
                        <h2 class="topic" id="{{ topic.id }}">{{ topic.topic_header }}</h2>
                        <img src="{{ topic.topic_pic.url }}" alt="No icon" width="100" height="100">
                    </td>
                    <td class="rate"><p>{{ topic.topic_rate_plus }} Likes |
                        {{ topic.topic_rate_minus }} Dislikes </p>
                    </td>
                    <td class="count">
                        {{ topic.topiccomments_set.count }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </tr>
{% endblock %}

templates/forum/login.html
<form action="/login" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" id="username">
    <label for="password">Password</label>
    <input type="password" name="password" id="password">
    <input class="button" type="submit" value="Enter">

</form>
<a href="/register">Registration</a>
{% if login_error %}<p class="error">{{ login_error }}</p>{% endif %}

templates/forum/register.html
<div>
    <form action="/register" method="post">
        {% csrf_token %}
        {{ form }}

        <input type="submit" value="Register">
    </form>
</div>

templates/forum/topic.html
{% extends 'forum/base.html' %}

{% block title %}{{ topic.topic_header }}{% endblock %}

{% block content %}
    <h1>{{ topic.topic_header }}</h1><hr>
    <pre>{{ topic.topic_text }}</pre><hr>
    <p>{{ topic.topic_rate_plus }} <a href="addlike/{{ topic.id }}">Like </a>
        {{ topic.topic_rate_minus }}<a href="adddislike/{{ topic.id }}">Dislike </a></p>
    <hr>
    {% if user.is_authenticated %}
        <div class="commentContainerW">
            <form action="{% url 'add_comment' topic.id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="button" value="Отправить">
            </form>
        </div>
    {% else %}
        <p class="error">Для отправки комментариев требуется авторизация</p>
    {% endif %}
    {% for comment in comments %}
        <div class="commentContainerR">
            <a class="user" href="/view/{{ comment.comments_by }}">{{ comment.comments_by }}</a>
            <p>{{ comment.comments_text }}</p>
            <p><strong>{{ comment.comments_pub_date }}</strong></p>
            <hr>
        </div>
    {% endfor %}
{% endblock %}

templates/forum/topic_old.html
{% extends 'forum/base.html' %}

{% block title %}{{ topic.topic_header }}{% endblock %}

{% block content %}
    <h1>{{ topic.topic_header }}</h1><hr>
    <pre>{{ topic.topic_text }}</pre><hr>
    <p>{{ topic.topic_rate_plus }} <a href="addlike/{{ topic.id }}">Like </a>
        {{ topic.topic_rate_minus }}<a href="adddislike/{{ topic.id }}">Dislike </a></p>
    <hr>
    {% if user %}
        <form action="topic/addcomment/{{ topic.id }}" method="post">
            <ul>
                <li type="none">
                    <label for="comment">Comment text:</label>
                </li>
                <li type="none">
                    <textarea cols=70 rows="4" type="text" name="comment" id="comment"></textarea>
                </li>
                <li type="none">
                    <input type="submit" class="button" value="Отправить">
                </li>
            </ul>
        </form>
    {% else %}
        <p class="error">Для отправки комментариев требуется авторизация</p>
    {% endif %}
    {% for comment in comments %}
    <a class="user" href="/view/{{ comment.comments_by }}">{{ comment.comments_by }}</a>
    <p>{{ comment.comments_text }}</p>
    <p><strong>{{ comment.comments_pub_date }}</strong></p>
        <hr>
    {% endfor %}
{% endblock %}

templates/forum/userprofile.html
{% extends 'forum/base.html' %}

{% block content %}
    <h4>{{ userview.username }} | ID: {{ userview.id }}</h4>
    <p>Кол-во комментариев: {{ userview.topiccomments_set.count }}</p>
    <p>Почта: {{ userview.email }}</p>
    <p>Последний раз был: {{ userview.last_login }}</p>
    <p>Зарегистрирован: {{ userview.date_joined }}</p>
    <form action="{% url 'private_messages_new' %}" method="post">{% csrf_token %}
        <input type="submit" class="btn" value="Написать">
    </form>

    {% if userview.id == req.user.id or req.user.is_superuser %}
    <p style="color: darkgreen">Hello... Its me...</p>
    {% endif %}
{% endblock %}